# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-09-20 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0001_initial'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='article2tag',
        #     unique_together=set([]),
        # ),
        # migrations.RemoveField(
        #     model_name='article2tag',
        #     name='article',
        # ),
        # migrations.RemoveField(
        #     model_name='article2tag',
        #     name='tag',
        # ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainmodels.Tag', verbose_name='标签类型'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default='男 ', max_length=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, 'OpenStack'), (4, 'Oracle'), (5, 'Mysql')], default=None),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        # migrations.DeleteModel(
        #     name='Article2Tag',
        # ),
    ]
