# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-09-25 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainmodels', '0002_auto_20220920_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fangwen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userfans',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='mainmodels.UserInfo', verbose_name='粉丝'),
        ),
        migrations.AlterField(
            model_name='userfans',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='mainmodels.UserInfo', verbose_name='博主'),
        ),
    ]
